:: RapidEnv environment profile
:: Project: RapidEnv
:: Tag: main
:: User: z0001wdm
:: Machine: mhfr015d
:: Do not edit this file manually
@ECHO OFF
set RAPID_ENV_HOME=D:\Projects\RapidEnv\sources\environment
set RAPIDBEANS_TAG=main
set RAPIDBEANS_HOME=D:\Projects\RapidEnv
set RAPIDBEANS_TOOLS_HOME=D:\Projects\RapidBeans\tools
set RAPIDBEANS_TOOLS_SITE=file:D:/ArchiveSoftware/Develop/Java
set HOME=H:
set RAPID_ENV_PROJECT_HOME=D:\Projects\RapidEnv\sources
set Path=D:\Projects\RapidBeans\tools\jdk\1.6.0_26\bin;D:\Projects\RapidBeans\tools\ant\1.8.2\bin;D:\Projects\RapidEnv\sources\environment\bin;C:\WINNT\system32;C:\WINNT;C:\WINNT\system32\wbem;C:\Program Files\Utimaco\SafeGuard Easy;D:\bin;D:\cygwin\bin;C:\Program Files\Git\bin
set JAVA_HOME=D:\Projects\RapidBeans\tools\jdk\1.6.0_26
set ANT_HOME=D:\Projects\RapidBeans\tools\ant\1.8.2
set M2_REPO=D:\Projects\RapidBeans\mavenrepo
set M2_HOME=D:\Projects\RapidBeans\tools\maven\2.2.1
set DOCBOOK_XSL_HOME=D:\Projects\RapidBeans\tools\net\sf\docbook-xsl\1.75.2
set ECLIPSE_WORKSPACE=D:\Projects\RapidEnv\eclipseworkspace
